#include "stdafx.h"
#include <age/editor/ObjectDefinition/ObjectDefinitionDocument.h>

#include <age/editor/imgui_widgets/imgui_widgets.h>
#include "imgui_internal.h" // for DockBuilder Api

#include <age/imgui/ImGuiPropertyEditor.h>
#include <age/scene/ScenePropertyTypes.h>
#include <age/script/ScriptRuntimeInstance.h>
#include <age/script/contexts/ScriptUpdateContext.h>
#include <age/script/BaseProperties.h>

#include <IconFontHeaders/IconsLucide.h>

#include <age/editor/ObjectDefinition/Commands/ChangePropertiesCommand.h>
#include <age/editor/ScriptEditor/ScriptEditor.h>
#include <age/editor/ScriptEditor/Commands/SetOverridenValueCommand.h>
#include <age/editor/CommandManager/CompositeCommand.h>

#include <age/editor/Editor.h>
#include <age/script/Script.h>
#include <age/script/ScriptNodeTypeRegistry.h>

#include "age/Application.h"
#include <age/animation/Skeleton.h>
#include <imgui.h>

constexpr int MAX_OBJECTDEFINITION_TEXT_LENGTH = 256;

using namespace Ag;



void ObjectDefinitionDocument::Init(std::string_view aPath)
{
	Document::Init(aPath);

	myViewport.Init();
	myViewport.GetGrid().SetGridLineExtreme(400.0f);
	myGraphics = Editor::GetEditor()->GetEditorGraphics().CreateObjectDefinitionGraphicsInterface();

	std::filesystem::path path = aPath;
	std::string filename = path.stem().string();

	StringId nameId = StringRegistry::RegisterOrGetString(filename.data());
	myObjectDefinition = Editor::GetEditor()->GetSceneObjectDefinitionManager().Get(nameId);
	// Assets can be generated by TextureCooker while the editor is running, so
	// the startup scan may not know about a newly-created TGO yet. Register it on
	// demand instead of dereferencing a null definition below.
	if (!myObjectDefinition)
		myObjectDefinition = Editor::GetEditor()->GetSceneObjectDefinitionManager().CreateOrGet(path);
	if (!myObjectDefinition)
		throw std::runtime_error("Could not load object definition");

	// A new object's Event Graph starts with the standard events, like a Blueprint's: nothing to
	// look up, just wire them to what should happen.
	{
		Script& graph = myObjectDefinition->EditEventGraph();
		if (graph.GetFirstNodeId().id == ScriptNodeId::InvalidId)
		{
			float y = 0.f;
			for (const char* name : { "Start", "Update", "On Collision Enter", "On Trigger Enter" })
			{
				const ScriptNodeTypeId type = ScriptNodeTypeRegistry::GetTypeId(name);
				if (type.id == ScriptNodeTypeId::InvalidId)
					continue;
				const ScriptNodeId id = graph.CreateNode(type, ScriptNodeTypeRegistry::CreateNode(type), { 0.f, y });
				ScriptCreationContext context(graph, id);
				graph.EditNode(id).Init(context);
				y += 190.f;
			}
		}
	}

	char buffer[512];
	char asterix[2] = { 0, 0 };

	sprintf_s(buffer, "%s%s###Document:%s", myObjectDefinition->GetName().GetString(), asterix, myObjectDefinition->GetPath());
	myImGuiName = StringRegistry::RegisterOrGetString(buffer);

	const struct { Panels panel; const char* title; } titles[] = {
		{ Panels::Components, "Components" },
		{ Panels::MyBlueprint, "My Blueprint" },
		{ Panels::Details, "Details" },
		{ Panels::Viewport, "Viewport" },
		{ Panels::EventGraph, "Event Graph" },
	};
	for (const auto& title : titles)
	{
		sprintf_s(buffer, "%s##Document:%s", title.title, aPath.data());
		myPanelWindowNames[(size_t)title.panel] = buffer;
	}

	Camera& camera = myViewport.GetCamera();
	Vector2i resolution = myViewport.GetViewportSize();
	camera.SetPerspectiveProjection(
		60,
		{
			(float)resolution.x,
			(float)resolution.y
		},
		0.1f,
		50000.0f
	);

	Vector3f cameraRotation = { 45, 45, 0 };

	camera.GetTransform().SetRotation(cameraRotation);
	myViewport.SetCameraRotation(cameraRotation);
	camera.GetTransform().SetPosition((camera.GetTransform().GetForward() * -myViewport.GetCameraFocusDistance()));
}

void ObjectDefinitionDocument::Save()
{
	myObjectDefinition->Save();

	mySaveUndoStackSize = myUndoStackSize;
}

void ObjectDefinitionDocument::Update(float aTimeDelta, InputManager& inputManager)
{
	aTimeDelta; inputManager;
	ObjectDefinitionDrawParameters params =
	{
	.viewport = &myViewport,
	.livePreviewData = &myLivePreviewData,
	.objectDefinition = myObjectDefinition,
	.selectedProperty = mySelectedProperty
			};
	myGraphics->Draw(params);

	char buffer[512];
	char asterix[2] = { 0, 0 };

	// Todo: all of this base imgui stuff should move to the Document base class
	if (mySaveUndoStackSize != myUndoStackSize)
		asterix[0] = '*';

	sprintf_s(buffer, "%s%s###Document:%s", myObjectDefinition->GetName().GetString(), asterix, myObjectDefinition->GetPath());

	// See SceneDocument.cpp's identical guard: GetDocumentDockSpaceSize() can
	// still be {0,0} on this document's opening frame, which asserts inside
	// DockBuilderSetNodeSize -- wait for a real size instead.
	const ImVec2 outerDockSize = Editor::GetEditor()->GetDocumentDockSpaceSize();
	if (!myIsDockingInitialized && outerDockSize.x > 0.0f && outerDockSize.y > 0.0f)
	{
		ImGui::DockBuilderSetNodeSize(Editor::GetEditor()->GetDocumentDockSpaceId(), outerDockSize);
		ImGui::DockBuilderDockWindow(buffer, Editor::GetEditor()->GetDocumentDockSpaceId());

		ImGui::DockBuilderFinish(Editor::GetEditor()->GetDocumentDockSpaceId());
	}

	ImGui::SetNextWindowClass(Editor::GetEditor()->GetDocumentWindowClass());
	ImGui::SetNextWindowDockID(Editor::GetEditor()->GetDocumentDockSpaceId(), ImGuiCond_Once);

	{
		ImGui::PushStyleVar(ImGuiStyleVar_WindowPadding, ImVec2(0, 0));
		ImGui::PushStyleVar(ImGuiStyleVar_WindowBorderSize, 1);

		bool open = true;
		ImGui::Begin(buffer, &open);
		if (myState == Document::State::Open && !open)
		{
			myState = Document::State::CloseRequested;
		}
		ImGui::PopStyleVar(2);

		DrawToolbar();

		ImVec2 docSpaceSize = ImGui::GetContentRegionAvail();
		ImGuiID dockSpaceId = ImGui::GetID("Document Dockspace");
		// todo: ImGui::GetContentRegionAvail() returns wrong result first time it seems. What to do instead?
		ImGui::DockSpace(dockSpaceId, docSpaceSize, ImGuiDockNodeFlags_AutoHideTabBar, &myDocumentWindowClass);

		if (!myIsDockingInitialized && docSpaceSize.x > 0.0f && docSpaceSize.y > 0.0f)
		{
			ImGuiID center = 0, left = 0, right = 0, leftBottom = 0;

			ImGui::DockBuilderRemoveNode(dockSpaceId); // clear any previous layout
			ImGui::DockBuilderAddNode(dockSpaceId, ImGuiDockNodeFlags_DockSpace);
			ImGui::DockBuilderSetNodeSize(dockSpaceId, docSpaceSize);

			center = dockSpaceId;

			// Components over My Blueprint on the left, Details on the right.
			ImGui::DockBuilderSplitNode(center, ImGuiDir_Left, 0.18f, &left, &center);
			ImGui::DockBuilderSplitNode(center, ImGuiDir_Right, 0.22f, &right, &center);
			ImGui::DockBuilderSplitNode(left, ImGuiDir_Down, 0.55f, &leftBottom, &left);

			ImGui::DockBuilderDockWindow(myPanelWindowNames[(size_t)Panels::Components].c_str(), left);
			ImGui::DockBuilderDockWindow(myPanelWindowNames[(size_t)Panels::MyBlueprint].c_str(), leftBottom);
			ImGui::DockBuilderDockWindow(myPanelWindowNames[(size_t)Panels::Details].c_str(), right);
			ImGui::DockBuilderDockWindow(myPanelWindowNames[(size_t)Panels::Viewport].c_str(), center);
			ImGui::DockBuilderDockWindow(myPanelWindowNames[(size_t)Panels::EventGraph].c_str(), center);

			ImGui::DockBuilderFinish(dockSpaceId);
			myIsDockingInitialized = true;
		}

		ImGui::End();
	}

	const Ag::Color color = Ag::Application::GetInstance()->GetClearColor();

	ImGui::PushStyleColor(ImGuiCol_WindowBg, ImVec4(color.myR, color.myG, color.myB, color.myA));
	ImGui::SetNextWindowClass(&myDocumentWindowClass);

	bool isViewportOrPropertiesFocused = false;

	ImGui::PushStyleVar(ImGuiStyleVar_WindowPadding, ImVec2(0, 0));
	ImGui::Begin(myPanelWindowNames[(size_t)Panels::Viewport].c_str());
	ImGui::PopStyleVar(1);

	isViewportOrPropertiesFocused = isViewportOrPropertiesFocused || ImGui::IsWindowFocused();
	myViewport.DrawAndUpdateViewportWindow(aTimeDelta, *this);

	ImGui::End();
	ImGui::PopStyleColor();

	ImGui::SetNextWindowClass(&myDocumentWindowClass);

	ImGui::Begin(myPanelWindowNames[(size_t)Panels::Components].c_str());
	DrawComponentsPanel();
	ImGui::End();

	ImGui::SetNextWindowClass(&myDocumentWindowClass);
	ImGui::Begin(myPanelWindowNames[(size_t)Panels::MyBlueprint].c_str());
	DrawMyBlueprintPanel();

	ImGui::End();

	ImGui::SetNextWindowClass(&myDocumentWindowClass);
	if (myShowEventGraphNextFrame)
	{
		ImGui::SetNextWindowFocus();
		myShowEventGraphNextFrame = false;
	}
	ImGui::Begin(myPanelWindowNames[(size_t)Panels::EventGraph].c_str());
	myGraphEditor.Display(myObjectDefinition->EditEventGraph(), myObjectDefinition, myLivePreviewData.pinToTrigger, myLivePreviewData.mode == LivePreviewMode::Running);
	ImGui::End();

	ImGui::SetNextWindowClass(&myDocumentWindowClass);

	isViewportOrPropertiesFocused = isViewportOrPropertiesFocused || ImGui::IsWindowFocused();
	ImGui::Begin(myPanelWindowNames[(size_t)Panels::Details].c_str());

	DrawDetailsPanel();

	ImGui::End();

	DrawAndUpdateLivePreview(aTimeDelta);
}

void ObjectDefinitionDocument::OnAction(CommandManager::Action action)
{
	if (action == CommandManager::Action::Do)
	{
		// If doing something when the undo stack is lower than when we saved, it means we can't get back to the saved state
		if (myUndoStackSize < mySaveUndoStackSize)
			mySaveUndoStackSize = -1;

		myUndoStackSize++;
	}
	if (action == CommandManager::Action::PostRedo)
	{
		myUndoStackSize++;
	}
	if (action == CommandManager::Action::PostUndo)
	{
		myUndoStackSize--;
	}
	if (action == CommandManager::Action::Clear)
	{
		myUndoStackSize = 0;
	}
}

namespace
{
	// The colour a pin of this type has in the graph, so a variable is recognisable there.
	ImU32 VariableColor(const PropertyTypeBase* type)
	{
		ScriptPin pin = {};
		pin.type = ScriptLinkType::Property;
		pin.dataType = type;
		const uint8_t* c = GetScriptLinkColor(pin);
		return IM_COL32(c[0], c[1], c[2], 255);
	}

	bool MatchesFilter(const char* text, const char* filter)
	{
		if (!filter || !*filter)
			return true;
		std::string lowerText(text), lowerFilter(filter);
		for (char& c : lowerText) c = (char)std::tolower((unsigned char)c);
		for (char& c : lowerFilter) c = (char)std::tolower((unsigned char)c);
		return lowerText.find(lowerFilter) != std::string::npos;
	}
}

void ObjectDefinitionDocument::DrawToolbar()
{
	ImGui::PushStyleVar(ImGuiStyleVar_WindowPadding, ImVec2(8.f, 5.f));
	ImGui::BeginChild("##ObjectToolbar", ImVec2(0.f, 34.f), ImGuiChildFlags_AlwaysUseWindowPadding, ImGuiWindowFlags_NoScrollbar);
	ImGui::PopStyleVar();

	if (ImGui::Button(ICON_LC_SAVE " Save"))
		Save();
	ImGui::SameLine();
	ImGui::TextDisabled("|");
	ImGui::SameLine();

	const ImVec2 size = ImVec2(28.f, 0.f);
	const bool running = myLivePreviewData.mode == LivePreviewMode::Running;
	const bool stopped = myLivePreviewData.mode == LivePreviewMode::Stopped;

	ImGui::BeginDisabled(running);
	if (ImGui::Button(ICON_LC_PLAY, size))
	{
		if (stopped)
		{
			for (const ScenePropertyDefinition& p : myObjectDefinition->GetProperties())
			{
				if ((p.flags & ScenePropertyFlags::IsDynamic) != ScenePropertyFlags::None)
					myLivePreviewData.dynamicProperties[p.name] = p.value;
				else
					myLivePreviewData.staticProperties[p.name] = p.value;
			}
			if (myObjectDefinition->HasEventGraph())
			{
				myLivePreviewData.graph = std::make_unique<ScriptRuntimeInstance>(myObjectDefinition->GetEventGraphSnapshot());
				myLivePreviewData.graph->Init();
			}
		}
		myLivePreviewData.mode = LivePreviewMode::Running;
	}
	ImGui::EndDisabled();
	if (ImGui::IsItemHovered(ImGuiHoveredFlags_AllowWhenDisabled))
		ImGui::SetTooltip("Run the Event Graph on this object in the viewport");

	ImGui::SameLine();
	ImGui::BeginDisabled(!running);
	if (ImGui::Button(ICON_LC_PAUSE, size))
		myLivePreviewData.mode = LivePreviewMode::Paused;
	ImGui::EndDisabled();

	ImGui::SameLine();
	ImGui::BeginDisabled(stopped);
	if (ImGui::Button(ICON_LC_SQUARE, size))
	{
		myLivePreviewData.mode = LivePreviewMode::Stopped;
		myLivePreviewData.poses.clear();
		myLivePreviewData.dynamicProperties.clear();
		myLivePreviewData.staticProperties.clear();
		myLivePreviewData.graph.reset();
		myLivePreviewData.frameNumber = 0;
	}
	ImGui::EndDisabled();

	ImGui::SameLine();
	ImGui::TextDisabled("%s", running ? "Running" : (stopped ? "Stopped" : "Paused"));

	if (myLivePreviewData.graph && myLivePreviewData.graph->GetScript().GetSequenceNumber() != myObjectDefinition->EditEventGraph().GetSequenceNumber())
	{
		ImGui::SameLine();
		ImGui::TextColored(ImVec4(0.95f, 0.75f, 0.3f, 1.f), ICON_LC_TRIANGLE_ALERT " Graph changed, stop and play again");
	}

	ImGui::SameLine();
	if (ImGui::Button(ICON_LC_SETTINGS))
		ImGui::OpenPopup("PreviewSettings");
	if (ImGui::IsItemHovered())
		ImGui::SetTooltip("Preview settings");
	if (ImGui::BeginPopup("PreviewSettings"))
	{
		if (myGraphics)
			myGraphics->DrawVisualPreviewSettings();
		ImGui::EndPopup();
	}

	ImGui::EndChild();
}

void ObjectDefinitionDocument::DrawComponentsPanel()
{
	if (ImGui::Button(ICON_LC_PLUS " Add"))
		ImGui::OpenPopup("AddComponentMenu");

	if (ImGui::BeginPopup("AddComponentMenu"))
	{
		for (const StringId& name : PropertyTypeRegistry::GetAllPropertyNames())
		{
			const PropertyTypeBase* type = PropertyTypeRegistry::GetPropertyType(name);
			if (!type->IsComponent())
				continue;

			// An object holds one of each component.
			bool present = false;
			for (const ScenePropertyDefinition& existing : myObjectDefinition->GetProperties())
				present |= existing.type == type;

			ImGui::BeginDisabled(present);
			if (ImGui::Selectable(name.GetString()))
			{
				ScenePropertyDefinition newProperty = {};
				newProperty.name = type->GetName();
				newProperty.type = type;
				newProperty.value = Property(type);
				newProperty.flags = ScenePropertyFlags::None;
				CommandManager::DoCommand(std::make_shared<ChangePropertiesCommand>(*myObjectDefinition, ChangePropertiesCommand::Action::Add, newProperty, ScenePropertyDefinition{}));
				mySelectedProperty = newProperty.name;
			}
			ImGui::EndDisabled();
		}
		ImGui::EndPopup();
	}
	ImGui::Separator();

	// The object itself is the root; components hang under it.
	char rootLabel[256];
	sprintf_s(rootLabel, "%s (Self)", myObjectDefinition->GetName().GetString());
	ImGuiTreeNodeFlags rootFlags = ImGuiTreeNodeFlags_DefaultOpen | ImGuiTreeNodeFlags_OpenOnArrow | ImGuiTreeNodeFlags_SpanAvailWidth;
	if (mySelectedProperty.IsEmpty())
		rootFlags |= ImGuiTreeNodeFlags_Selected;
	const bool rootOpen = ImGui::TreeNodeEx(rootLabel, rootFlags);
	if (ImGui::IsItemClicked())
		mySelectedProperty = {};

	if (rootOpen)
	{
		std::span<const ScenePropertyDefinition> properties = myObjectDefinition->GetProperties();
		for (int i = 0; i < properties.size(); i++)
		{
			if (!properties[i].type->IsComponent())
				continue;

			ImGuiTreeNodeFlags flags = ImGuiTreeNodeFlags_Leaf | ImGuiTreeNodeFlags_NoTreePushOnOpen | ImGuiTreeNodeFlags_SpanAvailWidth;
			if (mySelectedProperty == properties[i].name)
				flags |= ImGuiTreeNodeFlags_Selected;

			char label[256];
			sprintf_s(label, "%s  %s", ICON_LC_BOX, properties[i].name.GetString());
			ImGui::TreeNodeEx(label, flags);
			if (ImGui::IsItemClicked())
				mySelectedProperty = properties[i].name;

			if (ImGui::BeginPopupContextItem(properties[i].name.GetString()))
			{
				if (ImGui::Selectable(ICON_LC_TRASH_2 "  Remove"))
					CommandManager::DoCommand(std::make_shared<ChangePropertiesCommand>(*myObjectDefinition, ChangePropertiesCommand::Action::Remove, ScenePropertyDefinition{}, properties[i]));
				ImGui::EndPopup();
			}
		}
		ImGui::TreePop();
	}
}

void ObjectDefinitionDocument::DrawMyBlueprintPanel()
{
	static char filter[64] = "";

	if (ImGui::Button(ICON_LC_PLUS " Variable"))
		ImGui::OpenPopup("NewVariableType");

	if (ImGui::BeginPopup("NewVariableType"))
	{
		ImGui::TextDisabled("Type");
		ImGui::Separator();
		for (const StringId& name : PropertyTypeRegistry::GetAllPropertyNames())
		{
			const PropertyTypeBase* type = PropertyTypeRegistry::GetPropertyType(name);
			if (type->IsComponent())
				continue;

			ImGui::PushStyleColor(ImGuiCol_Text, ImGui::ColorConvertU32ToFloat4(VariableColor(type)));
			ImGui::TextUnformatted(ICON_LC_CIRCLE);
			ImGui::PopStyleColor();
			ImGui::SameLine();
			if (ImGui::Selectable(name.GetString()))
			{
				// "NewVar", made unique, ready to be renamed in Details.
				std::string base = "NewVar", unique = base;
				for (int suffix = 2;; ++suffix)
				{
					bool taken = false;
					for (const ScenePropertyDefinition& existing : myObjectDefinition->GetProperties())
						taken |= unique == existing.name.GetString();
					if (!taken)
						break;
					unique = base + std::to_string(suffix);
				}

				ScenePropertyDefinition newProperty = {};
				newProperty.name = StringRegistry::RegisterOrGetString(unique);
				newProperty.type = type;
				newProperty.value = Property(type);
				newProperty.flags = ScenePropertyFlags::IsDynamic | ScenePropertyFlags::IsPerInstance;
				newProperty.groupName = StringRegistry::RegisterOrGetString("Variables");
				CommandManager::DoCommand(std::make_shared<ChangePropertiesCommand>(*myObjectDefinition, ChangePropertiesCommand::Action::Add, newProperty, ScenePropertyDefinition{}));
				mySelectedProperty = newProperty.name;
			}
		}
		ImGui::EndPopup();
	}

	ImGui::SameLine();
	ImGui::SetNextItemWidth(-1.f);
	ImGui::InputTextWithHint("##variablesearch", ICON_LC_SEARCH " Search", filter, sizeof(filter));
	ImGui::Separator();

	ImGuiTreeNodeFlags sectionFlags = ImGuiTreeNodeFlags_DefaultOpen | ImGuiTreeNodeFlags_SpanAvailWidth;

	if (ImGui::CollapsingHeader("GRAPHS", sectionFlags))
	{
		ImGuiTreeNodeFlags flags = ImGuiTreeNodeFlags_Leaf | ImGuiTreeNodeFlags_NoTreePushOnOpen | ImGuiTreeNodeFlags_SpanAvailWidth;
		char label[64];
		sprintf_s(label, "%s  Event Graph", ICON_LC_WORKFLOW);
		ImGui::TreeNodeEx(label, flags);
		if (ImGui::IsItemClicked() || (ImGui::IsItemHovered() && ImGui::IsMouseDoubleClicked(0)))
			myShowEventGraphNextFrame = true;
	}

	if (ImGui::CollapsingHeader("VARIABLES", sectionFlags))
	{
		std::span<const ScenePropertyDefinition> properties = myObjectDefinition->GetProperties();
		int shown = 0;
		for (int i = 0; i < properties.size(); i++)
		{
			if (properties[i].type->IsComponent() || !MatchesFilter(properties[i].name.GetString(), filter))
				continue;
			++shown;

			ImGui::PushID(i);
			const bool selected = mySelectedProperty == properties[i].name;
			const ImVec2 rowStart = ImGui::GetCursorScreenPos();

			// Type colour dot, name, and the type on the right: same colours as the pins in the graph.
			ImGui::Selectable("##variable", selected, ImGuiSelectableFlags_SpanAllColumns);
			const bool clicked = ImGui::IsItemClicked();

			if (ImGui::BeginDragDropSource())
			{
				// Drop it in the Event Graph: a Get node, or a Set node with Alt held.
				struct Payload { PropertyTypeId type; StringId name; };
				Payload payload = { .type = properties[i].type->GetTypeId(), .name = properties[i].name };
				ImGui::SetDragDropPayload("property_payload", (void*)&payload, sizeof(payload));
				ImGui::Text("%s  (%s)", properties[i].name.GetString(), properties[i].type->GetName().GetString());
				ImGui::TextDisabled("Drop in the Event Graph. Hold Alt for Set.");
				ImGui::EndDragDropSource();
			}
			else if (clicked)
			{
				mySelectedProperty = properties[i].name;
			}

			const ImVec2 rowEnd = ImVec2(ImGui::GetItemRectMax().x, ImGui::GetItemRectMax().y);
			ImDrawList* draw = ImGui::GetWindowDrawList();
			const float lineHeight = ImGui::GetTextLineHeight();
			draw->AddCircleFilled(ImVec2(rowStart.x + 10.f, rowStart.y + lineHeight * 0.5f + 2.f), 5.f, VariableColor(properties[i].type));
			draw->AddText(ImVec2(rowStart.x + 24.f, rowStart.y + 1.f), ImGui::GetColorU32(ImGuiCol_Text), properties[i].name.GetString());
			const char* typeName = properties[i].type->GetName().GetString();
			const float typeWidth = ImGui::CalcTextSize(typeName).x;
			draw->AddText(ImVec2(rowEnd.x - typeWidth - 8.f, rowStart.y + 1.f), ImGui::GetColorU32(ImGuiCol_TextDisabled), typeName);

			if (ImGui::BeginPopupContextItem("VariableMenu"))
			{
				if (ImGui::Selectable(ICON_LC_TRASH_2 "  Remove"))
					CommandManager::DoCommand(std::make_shared<ChangePropertiesCommand>(*myObjectDefinition, ChangePropertiesCommand::Action::Remove, ScenePropertyDefinition{}, properties[i]));
				ImGui::EndPopup();
			}
			ImGui::PopID();
		}
		if (shown == 0)
			ImGui::TextDisabled(filter[0] ? "No variable matches" : "No variables yet. Press + Variable.");
	}
}

void ObjectDefinitionDocument::DrawDetailsPanel()
{
	char buffer[MAX_OBJECTDEFINITION_TEXT_LENGTH];

	std::span<const ScenePropertyDefinition> properties = myObjectDefinition->GetProperties();

	int selectedPropertyIndex = -1;

	for (int i = 0; i < properties.size(); i++)
	{
		if (mySelectedProperty == properties[i].name)
		{
			selectedPropertyIndex = i;
			break;
		}
	}

	if (selectedPropertyIndex != -1)
	{
		const ScenePropertyDefinition& property = properties[selectedPropertyIndex];
		ScenePropertyDefinition newProperty = property;
		bool hasChange = false;
		const bool isComponent = property.type->IsComponent();

		ImGui::Text("%s", property.name.GetString());
		ImGui::SameLine();
		ImGui::TextDisabled("(%s)", isComponent ? "Component" : property.type->GetName().GetString());
		ImGui::Separator();

		if (!isComponent && PropertyEditor::PropertyHeader("Variable"))
		{
			if (PropertyEditor::BeginPropertyTable())
			{
				{
					strncpy_s(buffer, property.name.GetString(), sizeof(buffer));
					buffer[sizeof(buffer) - 1] = '\0';

					PropertyEditor::PropertyLabel();

					ImGui::Text("Name");
					PropertyEditor::HelpMarker("Used to identify a variable. Has to be unique within an Object Definition");

					PropertyEditor::PropertyValue();

					ImGui::InputText("##Name", buffer, IM_ARRAYSIZE(buffer));

					if (ImGui::IsItemDeactivatedAfterEdit())
					{
						StringId newName = StringRegistry::RegisterOrGetString(buffer);
						if (newProperty.name != newName)
						{
							newProperty.name = newName;
							hasChange = true;
						}
					}

				}

				{
					strncpy_s(buffer, property.groupName.GetString(), sizeof(buffer));
					buffer[sizeof(buffer) - 1] = '\0';

					PropertyEditor::PropertyLabel();
					ImGui::Text("Group Name");
					PropertyEditor::HelpMarker("Group name is used to group properties in the property list");

					PropertyEditor::PropertyValue();
					ImGui::InputText("##Group Name", buffer, IM_ARRAYSIZE(buffer));

					if (ImGui::IsItemDeactivatedAfterEdit())
					{
						StringId newGroupName = StringRegistry::RegisterOrGetString(buffer);
						if (newProperty.groupName != newGroupName)
						{
							newProperty.groupName = newGroupName;
							hasChange = true;
						}
					}
				}

				{
					strncpy_s(buffer, property.description.GetString(), sizeof(buffer));
					buffer[sizeof(buffer) - 1] = '\0';

					PropertyEditor::PropertyLabel();
					ImGui::Text("Description");
					PropertyEditor::HelpMarker("Description of what the property is used for. Shows up in tooltips");

					PropertyEditor::PropertyValue();
					ImGui::InputText("##Description", buffer, IM_ARRAYSIZE(buffer));

					if (ImGui::IsItemDeactivatedAfterEdit())
					{
						StringId newDescription = StringRegistry::RegisterOrGetString(buffer);
						if (newProperty.description != newDescription)
						{
							newProperty.description = newDescription;
							hasChange = true;
						}
					}
				}

				{
					bool currentAllowInstanceOverride = (property.flags & ScenePropertyFlags::IsPerInstance) != ScenePropertyFlags::None;
					bool newAllowInstanceOverride = currentAllowInstanceOverride;

					PropertyEditor::PropertyLabel();
					ImGui::Text("Instance Editable");
					PropertyEditor::HelpMarker("Controls if the property is editable in instances of the objects. If true you can edit this property in scenes the object is placed");

					PropertyEditor::PropertyValue();
					ImGui::Checkbox("##Instance Editable", &newAllowInstanceOverride);

					if (newAllowInstanceOverride != currentAllowInstanceOverride)
					{
						newProperty.flags = (property.flags & ~ScenePropertyFlags::IsPerInstance) | (newAllowInstanceOverride ? ScenePropertyFlags::IsPerInstance : ScenePropertyFlags::None);
						hasChange = true;
					}
				}

				{
					bool currentIsDynamic = (property.flags & ScenePropertyFlags::IsDynamic) != ScenePropertyFlags::None;
					bool newIsDynamic = currentIsDynamic;

					PropertyEditor::PropertyLabel();
					ImGui::Text("Is Dynamic");
					PropertyEditor::HelpMarker("Dynamic properties are editable from scripts");

					PropertyEditor::PropertyValue();
					ImGui::Checkbox("##Is Dynamic", &newIsDynamic);

					if (newIsDynamic != currentIsDynamic)
					{
						newProperty.flags = (property.flags & ~ScenePropertyFlags::IsDynamic) | (newIsDynamic ? ScenePropertyFlags::IsDynamic : ScenePropertyFlags::None);
						hasChange = true;
					}
				}

				{
					StringId currentPropertyType = newProperty.type->GetName();
					StringId newPropertyType = currentPropertyType;

					PropertyEditor::PropertyLabel();
					ImGui::Text("Type");
					PropertyEditor::PropertyValue();
					if (ImGui::BeginCombo("##Type", currentPropertyType.GetString()))
					{
						std::span<StringId> allTypes = PropertyTypeRegistry::GetAllPropertyNames();

						for (const StringId& name : allTypes)
						{
							bool isSelected = name == currentPropertyType;
							if (ImGui::Selectable(name.GetString(), isSelected))
							{
								newPropertyType = name;
							}

							if (isSelected)
							{
								ImGui::SetItemDefaultFocus();
							}
						}

						ImGui::EndCombo();
					}

					if (newPropertyType != currentPropertyType)
					{
						newProperty.type = PropertyTypeRegistry::GetPropertyType(newPropertyType);
						newProperty.value = Property(newProperty.type);

						hasChange = true;
					}
				}

				PropertyEditor::EndPropertyTable();
			}
		}

		if (PropertyEditor::PropertyHeader(isComponent ? "Component" : "Default Value"))
		{
			if (PropertyEditor::BeginPropertyTable())
			{			
				if (newProperty.value.ShowImGuiEditor(property.name.GetString(), property.description.GetString()))
				{
					hasChange = true;
				}	

				PropertyEditor::EndPropertyTable();
			}
		}


		if (hasChange)
		{
			std::shared_ptr<ChangePropertiesCommand> command = std::make_shared<ChangePropertiesCommand>(*myObjectDefinition, ChangePropertiesCommand::Action::Edit, newProperty, property);

			if (newProperty.name != property.name && myObjectDefinition->HasEventGraph())
			{
				// A renamed variable keeps working: the Get / Set nodes that named it follow the rename,
				// as one undo step with the rename itself.
				auto composite = std::make_shared<CompositeCommand>("Rename Variable");
				composite->Do(command);

				Script& graph = myObjectDefinition->EditEventGraph();
				for (ScriptNodeId node = graph.GetFirstNodeId(); node.id != ScriptNodeId::InvalidId; node = graph.GetNextNodeId(node))
				{
					size_t count;
					const ScriptPinId* inputs = graph.GetInputPins(node, count);
					for (size_t i = 0; i < count; i++)
					{
						const ScriptPin& pin = graph.GetPin(inputs[i]);
						if (pin.name != "Name"_tgaid || pin.dataType != GetPropertyType<StringId>() || !pin.overridenValue.HasValue())
							continue;
						const StringId* current = pin.overridenValue.Get<StringId>();
						if (current && *current == property.name)
							composite->Do(std::make_shared<SetOverridenValueCommand>(graph, myGraphEditor.GetSelection(), inputs[i], Property::Create<StringId>(newProperty.name)));
					}
				}
				CommandManager::DoCommand(composite);
			}
			else
			{
				CommandManager::DoCommand(command);
			}

			mySelectedProperty = newProperty.name;
		}
	}
	else
	{
		ImGui::TextDisabled("Select a component or a variable to see its details.");
	}
}

void ObjectDefinitionDocument::DrawAndUpdateLivePreview(float deltaTime)
{
	if (myLivePreviewData.mode == LivePreviewMode::Running)
	{
		myLivePreviewData.frameNumber++;

		ScriptUpdateContext scriptUpdateContext;

		scriptUpdateContext.deltaTime = deltaTime;
		scriptUpdateContext.frameNumber = myLivePreviewData.frameNumber;
		scriptUpdateContext.dynamicProperties = &myLivePreviewData.dynamicProperties;
		scriptUpdateContext.staticProperties = &myLivePreviewData.staticProperties;

		if (myLivePreviewData.graph)
		{
			if (myLivePreviewData.pinToTrigger.id != ScriptPinId::InvalidId)
			{
				myLivePreviewData.graph->TriggerPin(myLivePreviewData.pinToTrigger, scriptUpdateContext);
				myLivePreviewData.pinToTrigger.id = ScriptPinId::InvalidId;
			}
			myLivePreviewData.graph->Update(scriptUpdateContext);
		}
		
		std::span<const ScenePropertyDefinition> properties = myObjectDefinition->GetProperties();
		for (int propertyIndex = 0; propertyIndex < properties.size(); propertyIndex++)
		{
			const ScenePropertyDefinition& property = properties[propertyIndex];

			if (property.type == GetPropertyType<CopyOnWriteWrapper<SceneModel>>())
			{
				StringId path = property.value.Get<CopyOnWriteWrapper<SceneModel>>()->Get().path;
				std::shared_ptr<const Skeleton> skeleton = GetSkeleton(path.GetString());

				if (skeleton)
				{
					// todo: remove this per frame allocation...
					std::string poseNameString = property.name.GetString();
					poseNameString += "_pose";

					StringId poseName = StringRegistry::RegisterOrGetString(poseNameString);

					auto it = myLivePreviewData.dynamicProperties.find(poseName);
					if (it != myLivePreviewData.dynamicProperties.end())
					{
						PoseAndMotion* poseAndMotion = it->second.Get<PoseAndMotion>();

						if (poseAndMotion && poseAndMotion->poseGenerator)
						{
							std::string syncedTimeNameString = property.name.GetString();
							syncedTimeNameString += "_syncedTime";

							StringId syncedTimeName = StringRegistry::RegisterOrGetString(syncedTimeNameString);

							auto timeIt = myLivePreviewData.dynamicProperties.find(syncedTimeName);

							float syncedTime = 0.f;
							if (timeIt != myLivePreviewData.dynamicProperties.end())
							{
								float* time = timeIt->second.Get<float>();
								if (time)
									syncedTime = *time;
							}

							if (poseAndMotion->desiredSyncedPlaybackRateWeight > 0.f)
							{
								syncedTime += poseAndMotion->desiredSyncedPlaybackRate * deltaTime;
								syncedTime -= floor(syncedTime);
							}

							myLivePreviewData.dynamicProperties[syncedTimeName] = Property::Create<float>(syncedTime);

							PoseGenerationContext context = {};
							context.deltaTime = deltaTime;
							context.frameNumber = myLivePreviewData.frameNumber;
							context.syncedPlaybackTime = syncedTime;
							context.skeleton = skeleton;

							LocalSpacePose pose;
							poseAndMotion->poseGenerator->GeneratePose(context, pose);

							skeleton->ConvertPoseToModelSpace(pose, myLivePreviewData.poses[property.name]);
						}

						// removing pose every frame in case a script is stopped and the pose remains
						// otherwise we could get a dangling pointer
						myLivePreviewData.dynamicProperties.erase(it);
					}

				}
			}
		}
	}

	static std::set<StringId> propertyNames;

	propertyNames.clear();

	for (auto p : myLivePreviewData.dynamicProperties)
	{
		propertyNames.insert(p.first);
	}

	for (auto p : myLivePreviewData.staticProperties)
	{
		propertyNames.insert(p.first);
	}
	if (!propertyNames.empty() && PropertyEditor::PropertyHeader("Live Property Values") && PropertyEditor::BeginPropertyTable())
	{
		for (auto propertyName : propertyNames)
		{
			ImGui::PushID(propertyName.GetString());

			auto it = myLivePreviewData.dynamicProperties.find(propertyName);
			if (it == myLivePreviewData.dynamicProperties.end())
				it = myLivePreviewData.staticProperties.find(propertyName);

			it->second.ShowImGuiEditor(propertyName.GetString());

			ImGui::PopID();
		}

		PropertyEditor::EndPropertyTable();
	}
}

void ObjectDefinitionDocument::HandleDrop()
{

}

void ObjectDefinitionDocument::BeginDragSelection(Vector2f mousePos)
{
	mousePos;
}

void ObjectDefinitionDocument::EndDragSelection(Vector2f mousePos, bool isShiftDown)
{
	mousePos;
	isShiftDown;
}

void ObjectDefinitionDocument::ClickSelection(Vector2f mousePos, uint32_t selectedId, bool isShiftDown)
{
	mousePos;
	isShiftDown;

	if (selectedId > 0)
	{
		int propertyIndex = selectedId - 1;

		std::span<const ScenePropertyDefinition> properties = myObjectDefinition->GetProperties();

		if (propertyIndex < properties.size())
		{
			mySelectedProperty = properties[propertyIndex].name;
		}
	}
	else
	{
		mySelectedProperty = {};
	}
}

void ObjectDefinitionDocument::BeginTransformation()
{

}

void ObjectDefinitionDocument::UpdateTransformation(const Vector3f& referencePosition, const Matrix4x4f& transform)
{
	referencePosition;
	transform;
}

void ObjectDefinitionDocument::EndTransformation()
{
}

Vector3f ObjectDefinitionDocument::CalculateSelectionPosition()
{
	return {};
}

Matrix4x4f ObjectDefinitionDocument::CalculateSelectionOrientation()
{
	return {};
}

bool ObjectDefinitionDocument::HasTransformableSelection()
{
	return false;
}
